// Generate a self-contained page with the real UI, animated model, CSS and embedded font.
// No browser launch or CDP connection is used.
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { build } from 'esbuild';
const out = new URL('../artifacts/home-preview/', import.meta.url);
await mkdir(out, { recursive: true });
let css = await readFile(new URL('../src/client/style.css', import.meta.url), 'utf8');
for (const match of css.matchAll(/url\('(?<path>\/fonts\/[^']+)'\)/g)) {
    const font = await readFile(new URL(`../public${match.groups!.path}`, import.meta.url));
    css = css.replace(match[0], `url('data:font/ttf;base64,${font.toString('base64')}')`);
}
const result = await build({ entryPoints: ['tests/home-preview-client.ts'], bundle: true, write: false, format: 'iife', minify: true, define: { 'import.meta.env.DEV': 'false' } });
const script = result.outputFiles[0].text.replace(/<\/script/gi, '<\\/script');
await writeFile(new URL('index.html', out), `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"><title>Furo · Home preview</title><style>${css}</style></head><body><canvas id="game" aria-hidden="true"></canvas><div id="ui"></div><script>${script}</script></body></html>`);
await writeFile(new URL('README.md', out), `Generated by npm run preview:home.\n\nServe the repository (for example python3 -m http.server 4174) and open /artifacts/home-preview/index.html. Everything is embedded; no game server or asset requests are required.\n\nScreenshot at 1280×800, 1440×900, 844×390 and 667×375. Await window.__homePreview.ready and document.fonts.ready. The character is the production Showroom with its idle animation; class buttons and callsign editing are interactive. Add #vince, #triggerman or #runngun to review other classes, or #join to review the code form. Create/join networking is covered by the live app tests, not this visual fixture.\n\nNo browser was launched in the sandbox.\n`);
console.log('Generated artifacts/home-preview/index.html (animated 3D character; embedded JS, CSS and font).');
